// Generated by sekai-chisei capability codegen. DO NOT EDIT.
// catalog_version="sha256:fixture-catalog"
// namespace="demo"
// principal="alice"

export const GENERATED_CATALOG_VERSION = "sha256:fixture-catalog";
export const GENERATED_NAMESPACE = "demo";
export const GENERATED_PRINCIPAL = "alice";
export const ALLOWED_CAPABILITIES = ["sekai.action.assign_color"] as const;

export interface SdkInvocation {
  catalog_version: string;
  namespace: string;
  principal: string;
  capability: string;
  operation_id: string;
  input_type: string;
  output_type: string;
  input: Record<string, unknown>;
}

const CAPABILITIES = {
  "sekai.action.assign_color": {
    name: "sekai.action.assign_color",
    input_type: "sekai.ListObjectsRequest",
    output_type: "sekai.ListObjectsResponse",
    kind: "query",
  },
} as const;

function invoke(
  capability: { name: string; input_type: string; output_type: string },
  operationId: string,
  input: Record<string, unknown>,
): SdkInvocation {
  if (!(ALLOWED_CAPABILITIES as readonly string[]).includes(capability.name)) {
    throw new Error(`capability not in generated scope: ${capability.name}`);
  }
  if (!operationId.trim()) throw new Error("operation_id required");
  return {
    catalog_version: GENERATED_CATALOG_VERSION,
    namespace: GENERATED_NAMESPACE,
    principal: GENERATED_PRINCIPAL,
    capability: capability.name,
    operation_id: operationId,
    input_type: capability.input_type,
    output_type: capability.output_type,
    input,
  };
}

export function nativeMetadata(call: SdkInvocation): Record<string, string> {
  if (!(ALLOWED_CAPABILITIES as readonly string[]).includes(call.capability)) {
    throw new Error(`capability not in generated scope: ${call.capability}`);
  }
  if (call.namespace !== GENERATED_NAMESPACE || call.principal !== GENERATED_PRINCIPAL
      || call.catalog_version !== GENERATED_CATALOG_VERSION) {
    throw new Error("invocation context does not match generated scope");
  }
  if (!call.operation_id.trim()) throw new Error("operation_id required");
  return {
    "x-principal": call.principal,
    "x-sekai-namespace": call.namespace,
    "x-sekai-capability": call.capability,
    "x-sekai-operation-id": call.operation_id,
    "x-chisei-work-unit": call.operation_id,
    "x-sekai-catalog-version": call.catalog_version,
  };
}

export function scopeAllows(capability: string): boolean {
  return (ALLOWED_CAPABILITIES as readonly string[]).includes(capability);
}

export class ScopedCapabilityClient {

  // Invoke sekai.action.assign_color
  sekaiActionAssignColor(operationId: string, input: Record<string, unknown>): SdkInvocation {
    return invoke(CAPABILITIES["sekai.action.assign_color"]!, operationId, input);
  }
}
