// Generated by sekai-chisei HTTP projection codegen. DO NOT EDIT.
// contract=sekai.http-projection/v1

export const HTTP_PROJECTION_CONTRACT = "sekai.http-projection/v1";
export const HTTP_UNARY_METHODS = [
  { service: "sekai.SekaiService", rpc: "ApplySourceBatch" },
  { service: "sekai.SekaiService", rpc: "GetSourceSyncState" },
  { service: "sekai.SekaiService", rpc: "GetPublishedDefinitionRevision" },
  { service: "sekai.SekaiService", rpc: "CreateObject" },
  { service: "sekai.SekaiService", rpc: "GetObject" },
  { service: "sekai.SekaiService", rpc: "UpdateObject" },
  { service: "sekai.SekaiService", rpc: "DeleteObject" },
  { service: "sekai.SekaiService", rpc: "ListObjects" },
  { service: "sekai.SekaiService", rpc: "EvaluateObjectSet" },
  { service: "sekai.SekaiService", rpc: "ReadObjectChangeSubscription" },
  { service: "sekai.SekaiService", rpc: "PutObjectSecurityPolicyRevision" },
  { service: "sekai.SekaiService", rpc: "ActivateObjectSecurityPolicies" },
  { service: "sekai.SekaiService", rpc: "GetObjectSecurityActivation" },
  { service: "sekai.SekaiService", rpc: "FindByExternalId" },
  { service: "sekai.SekaiService", rpc: "FindByProperty" },
  { service: "sekai.SekaiService", rpc: "CreateLink" },
  { service: "sekai.SekaiService", rpc: "DeleteLink" },
  { service: "sekai.SekaiService", rpc: "GetLinks" },
  { service: "sekai.SekaiService", rpc: "Traverse" },
  { service: "sekai.SekaiService", rpc: "DiscoverCapabilities" },
  { service: "sekai.SekaiService", rpc: "ListSchemaTypes" },
  { service: "sekai.SekaiService", rpc: "CreateSchemaType" },
  { service: "sekai.SekaiService", rpc: "CreateOntologyClass" },
  { service: "sekai.SekaiService", rpc: "CreateOntologyRelation" },
  { service: "sekai.SekaiService", rpc: "CreateDataset" },
  { service: "sekai.SekaiService", rpc: "UpdateDataset" },
  { service: "sekai.SekaiService", rpc: "AppendRows" },
  { service: "sekai.SekaiService", rpc: "QueryRows" },
  { service: "sekai.SekaiService", rpc: "CreateGrant" },
  { service: "sekai.SekaiService", rpc: "DeleteGrant" },
  { service: "sekai.SekaiService", rpc: "ListGrants" },
  { service: "sekai.SekaiService", rpc: "CheckAccess" },
  { service: "sekai.SekaiService", rpc: "PutGovernedActionType" },
  { service: "sekai.SekaiService", rpc: "SubmitActionInstance" },
  { service: "sekai.SekaiService", rpc: "DescribeObjectAction" },
  { service: "sekai.SekaiService", rpc: "PreviewObjectAction" },
  { service: "sekai.SekaiService", rpc: "GetActionInstance" },
  { service: "sekai.SekaiService", rpc: "GetActionEffect" },
  { service: "sekai.SekaiService", rpc: "ListActionEffects" },
  { service: "sekai.SekaiService", rpc: "CreateCredential" },
  { service: "sekai.SekaiService", rpc: "RotateCredential" },
  { service: "sekai.SekaiService", rpc: "RevokeCredential" },
  { service: "sekai.SekaiService", rpc: "ListCredentials" },
  { service: "sekai.SekaiService", rpc: "RegisterEvidenceSchema" },
  { service: "sekai.SekaiService", rpc: "SubmitEvidence" },
  { service: "chisei.ChiseiService", rpc: "ExecuteEvaluationManifest" },
  { service: "chisei.ChiseiService", rpc: "AuthorizeExternalAction" },
  { service: "chisei.ChiseiService", rpc: "TransitionExternalAction" },
  { service: "chisei.ChiseiService", rpc: "RedeemExternalActionPermit" },
  { service: "chisei.ChiseiService", rpc: "RecordUsage" },
  { service: "chisei.ChiseiService", rpc: "SetBudgetLimit" },
  { service: "chisei.ChiseiService", rpc: "DecideGatewayExecution" },
  { service: "chisei.ChiseiService", rpc: "SetNamespacePolicy" },
  { service: "chisei.ChiseiService", rpc: "PlanExecution" },
  { service: "chisei.ChiseiService", rpc: "PlanContentExecution" },
  { service: "chisei.ChiseiService", rpc: "ReportOperationEvent" },
  { service: "chisei.ChiseiService", rpc: "GetOperationReceipt" },
  { service: "chisei.ChiseiService", rpc: "GetQualityTrend" },
  { service: "chisei.ChiseiService", rpc: "ClaimGatewayDispatch" },
  { service: "chisei.ChiseiService", rpc: "PutEvaluationPlan" },
  { service: "chisei.ChiseiService", rpc: "ResolveEvaluationPlan" },
] as const;

export async function invokeHttpJson<T>(
  baseUrl: string,
  service: string,
  rpc: string,
  body: unknown,
  authorization: string,
  headers: Record<string, string> = {},
): Promise<T> {
  const allowed = HTTP_UNARY_METHODS.some((method) => method.service === service && method.rpc === rpc);
  if (!allowed) throw new Error(`rpc is not on the HTTP/JSON projection: ${service}/${rpc}`);
  const response = await fetch(`${baseUrl.replace(/\/$/, "")}/${service}/${rpc}`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization,
      ...headers,
    },
    body: JSON.stringify(body ?? {}),
  });
  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload.message ?? response.statusText);
  }
  return payload as T;
}
