"""Generated by sekai-chisei HTTP projection codegen. DO NOT EDIT."""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Any

HTTP_PROJECTION_CONTRACT = "sekai.http-projection/v1"
HTTP_UNARY_METHODS = (
    ("sekai.SekaiService", "ApplySourceBatch"),
    ("sekai.SekaiService", "GetSourceSyncState"),
    ("sekai.SekaiService", "GetPublishedDefinitionRevision"),
    ("sekai.SekaiService", "CreateObject"),
    ("sekai.SekaiService", "GetObject"),
    ("sekai.SekaiService", "UpdateObject"),
    ("sekai.SekaiService", "DeleteObject"),
    ("sekai.SekaiService", "ListObjects"),
    ("sekai.SekaiService", "EvaluateObjectSet"),
    ("sekai.SekaiService", "ReadObjectChangeSubscription"),
    ("sekai.SekaiService", "PutObjectSecurityPolicyRevision"),
    ("sekai.SekaiService", "ActivateObjectSecurityPolicies"),
    ("sekai.SekaiService", "GetObjectSecurityActivation"),
    ("sekai.SekaiService", "FindByExternalId"),
    ("sekai.SekaiService", "FindByProperty"),
    ("sekai.SekaiService", "CreateLink"),
    ("sekai.SekaiService", "DeleteLink"),
    ("sekai.SekaiService", "GetLinks"),
    ("sekai.SekaiService", "Traverse"),
    ("sekai.SekaiService", "DiscoverCapabilities"),
    ("sekai.SekaiService", "ListSchemaTypes"),
    ("sekai.SekaiService", "CreateSchemaType"),
    ("sekai.SekaiService", "CreateOntologyClass"),
    ("sekai.SekaiService", "CreateOntologyRelation"),
    ("sekai.SekaiService", "CreateDataset"),
    ("sekai.SekaiService", "UpdateDataset"),
    ("sekai.SekaiService", "AppendRows"),
    ("sekai.SekaiService", "QueryRows"),
    ("sekai.SekaiService", "CreateGrant"),
    ("sekai.SekaiService", "DeleteGrant"),
    ("sekai.SekaiService", "ListGrants"),
    ("sekai.SekaiService", "CheckAccess"),
    ("sekai.SekaiService", "PutGovernedActionType"),
    ("sekai.SekaiService", "SubmitActionInstance"),
    ("sekai.SekaiService", "DescribeObjectAction"),
    ("sekai.SekaiService", "PreviewObjectAction"),
    ("sekai.SekaiService", "GetActionInstance"),
    ("sekai.SekaiService", "GetActionEffect"),
    ("sekai.SekaiService", "ListActionEffects"),
    ("sekai.SekaiService", "CreateCredential"),
    ("sekai.SekaiService", "RotateCredential"),
    ("sekai.SekaiService", "RevokeCredential"),
    ("sekai.SekaiService", "ListCredentials"),
    ("sekai.SekaiService", "RegisterEvidenceSchema"),
    ("sekai.SekaiService", "SubmitEvidence"),
    ("chisei.ChiseiService", "AuthorizeExternalAction"),
    ("chisei.ChiseiService", "TransitionExternalAction"),
    ("chisei.ChiseiService", "RedeemExternalActionPermit"),
    ("chisei.ChiseiService", "RecordUsage"),
    ("chisei.ChiseiService", "SetBudgetLimit"),
    ("chisei.ChiseiService", "DecideGatewayExecution"),
    ("chisei.ChiseiService", "SetNamespacePolicy"),
    ("chisei.ChiseiService", "PlanExecution"),
    ("chisei.ChiseiService", "PlanContentExecution"),
    ("chisei.ChiseiService", "ReportOperationEvent"),
    ("chisei.ChiseiService", "GetOperationReceipt"),
    ("chisei.ChiseiService", "GetQualityTrend"),
    ("chisei.ChiseiService", "ClaimGatewayDispatch"),
)


def invoke_http_json(
    base_url: str,
    service: str,
    rpc: str,
    body: dict[str, Any] | None,
    authorization: str,
    headers: dict[str, str] | None = None,
) -> Any:
    if (service, rpc) not in HTTP_UNARY_METHODS:
        raise ValueError(f"rpc is not on the HTTP/JSON projection: {service}/{rpc}")
    request = urllib.request.Request(
        f"{base_url.rstrip('/')}/{service}/{rpc}",
        data=json.dumps({} if body is None else body).encode(),
        method="POST",
        headers={
            "content-type": "application/json",
            "authorization": authorization,
            **(headers or {}),
        },
    )
    try:
        with urllib.request.urlopen(request) as response:
            return json.load(response)
    except urllib.error.HTTPError as error:
        payload = json.loads(error.read().decode() or "{}")
        raise RuntimeError(payload.get("message") or error.reason) from error
