# Generated by sekai-chisei ontology codegen. DO NOT EDIT.
# contract_version="sekai.ontology-client/v1"
# namespace="demo"
# revision_digest="sha256:df76a10f45c87ebe11b97f282ff213733127694dae6594ffdef399866606749e"

from __future__ import annotations

from typing import NotRequired, TypedDict

GENERATED_CONTRACT_VERSION = "sekai.ontology-client/v1"
GENERATED_NAMESPACE = "demo"
GENERATED_REVISION_DIGEST = "sha256:df76a10f45c87ebe11b97f282ff213733127694dae6594ffdef399866606749e"
ALLOWED_MEMBERS = ["action_type:Assign", "function:CountOpen", "link_type:AssignedTo", "object_type:Ticket"]

class Assign(TypedDict):
    assignee: NotRequired[str]

class CountOpen(TypedDict):
    status: str

class AssignedTo(TypedDict):
    pass

class Ticket(TypedDict):
    title: str

class OntologyInvocation(TypedDict):
    contract_version: str
    namespace: str
    revision_digest: str
    member_kind: str
    member_id: str
    operation_id: str
    input: dict[str, object]


def scope_allows(member_kind: str, member_id: str) -> bool:
    return f"{member_kind}:{member_id}" in ALLOWED_MEMBERS


def bind_live_revision(live_revision_digest: str) -> None:
    if live_revision_digest != GENERATED_REVISION_DIGEST:
        raise ValueError("ontology client revision pin is stale")


def invoke(member_kind: str, member_id: str, operation_id: str, input: object) -> OntologyInvocation:
    if not scope_allows(member_kind, member_id):
        raise ValueError("member is not in generated scope")
    if not operation_id.strip():
        raise ValueError("operation_id required")
    payload = dict(input) if isinstance(input, dict) else {}
    return {
        "contract_version": GENERATED_CONTRACT_VERSION,
        "namespace": GENERATED_NAMESPACE,
        "revision_digest": GENERATED_REVISION_DIGEST,
        "member_kind": member_kind,
        "member_id": member_id,
        "operation_id": operation_id,
        "input": payload,
    }


def native_metadata(call: OntologyInvocation) -> dict[str, str]:
    if not scope_allows(call["member_kind"], call["member_id"]):
        raise ValueError("member is not in generated scope")
    if (
        call["namespace"] != GENERATED_NAMESPACE
        or call["revision_digest"] != GENERATED_REVISION_DIGEST
        or call["contract_version"] != GENERATED_CONTRACT_VERSION
    ):
        raise ValueError("invocation context does not match generated scope")
    if not call["operation_id"].strip():
        raise ValueError("operation_id required")
    return {
        "x-sekai-namespace": call["namespace"],
        "x-sekai-definition-revision": call["revision_digest"],
        "x-sekai-member-kind": call["member_kind"],
        "x-sekai-member-id": call["member_id"],
        "x-sekai-operation-id": call["operation_id"],
    }


class ScopedOntologyClient:

    def assign(self, operation_id: str, input: Assign) -> OntologyInvocation:
        return invoke("action_type", "Assign", operation_id, input)

    def count_open(self, operation_id: str, input: CountOpen) -> OntologyInvocation:
        return invoke("function", "CountOpen", operation_id, input)

    def assigned_to(self, operation_id: str, input: AssignedTo) -> OntologyInvocation:
        return invoke("link_type", "AssignedTo", operation_id, input)

    def ticket(self, operation_id: str, input: Ticket) -> OntologyInvocation:
        return invoke("object_type", "Ticket", operation_id, input)
