// Generated by sekai-chisei ontology codegen. DO NOT EDIT.
// contract_version="sekai.ontology-client/v1"
// namespace="demo"
// revision_digest="sha256:df76a10f45c87ebe11b97f282ff213733127694dae6594ffdef399866606749e"

export const GENERATED_CONTRACT_VERSION = "sekai.ontology-client/v1";
export const GENERATED_NAMESPACE = "demo";
export const GENERATED_REVISION_DIGEST = "sha256:df76a10f45c87ebe11b97f282ff213733127694dae6594ffdef399866606749e";
export const ALLOWED_MEMBERS = ["action_type:Assign", "function:CountOpen", "link_type:AssignedTo", "object_type:Ticket"] as const;

export interface Assign {
  assignee?: string;
}

export interface CountOpen {
  status: string;
}

export interface AssignedTo {}

export interface Ticket {
  title: string;
}

export interface OntologyInvocation {
  contract_version: string;
  namespace: string;
  revision_digest: string;
  member_kind: string;
  member_id: string;
  operation_id: string;
  input: Record<string, unknown>;
}

export function scopeAllows(memberKind: string, memberId: string): boolean {
  return (ALLOWED_MEMBERS as readonly string[]).includes(`${memberKind}:${memberId}`);
}

export function bindLiveRevision(liveRevisionDigest: string): void {
  if (liveRevisionDigest !== GENERATED_REVISION_DIGEST) {
    throw new Error("ontology client revision pin is stale");
  }
}

export function invoke<T extends object>(
  memberKind: string,
  memberId: string,
  operationId: string,
  input: T,
): OntologyInvocation {
  if (!scopeAllows(memberKind, memberId)) {
    throw new Error("member is not in generated scope");
  }
  if (!operationId.trim()) throw new Error("operation_id required");
  return {
    contract_version: GENERATED_CONTRACT_VERSION,
    namespace: GENERATED_NAMESPACE,
    revision_digest: GENERATED_REVISION_DIGEST,
    member_kind: memberKind,
    member_id: memberId,
    operation_id: operationId,
    input: { ...input } as Record<string, unknown>,
  };
}

export function nativeMetadata(call: OntologyInvocation): Record<string, string> {
  if (!scopeAllows(call.member_kind, call.member_id)) {
    throw new Error("member is not in generated scope");
  }
  if (call.namespace !== GENERATED_NAMESPACE
      || call.revision_digest !== GENERATED_REVISION_DIGEST
      || call.contract_version !== GENERATED_CONTRACT_VERSION) {
    throw new Error("invocation context does not match generated scope");
  }
  if (!call.operation_id.trim()) throw new Error("operation_id required");
  return {
    "x-sekai-namespace": call.namespace,
    "x-sekai-definition-revision": call.revision_digest,
    "x-sekai-member-kind": call.member_kind,
    "x-sekai-member-id": call.member_id,
    "x-sekai-operation-id": call.operation_id,
  };
}

export class ScopedOntologyClient {

  assign(operationId: string, input: Assign): OntologyInvocation {
    return invoke("action_type", "Assign", operationId, input);
  }

  countOpen(operationId: string, input: CountOpen): OntologyInvocation {
    return invoke("function", "CountOpen", operationId, input);
  }

  assignedTo(operationId: string, input: AssignedTo): OntologyInvocation {
    return invoke("link_type", "AssignedTo", operationId, input);
  }

  ticket(operationId: string, input: Ticket): OntologyInvocation {
    return invoke("object_type", "Ticket", operationId, input);
  }
}
