//! Generated HTTP/JSON clients for the stable unary projection (#875).
//!
//! The clients are a transport projection of the ADR 0071 maturity table.
//! They do not invent RPCs, authorization, or a second resource model.

use crate::http_projection::HTTP_PROJECTION_CONTRACT;
use crate::rpc_maturity::{RpcClassification, RpcMaturityTable};

const STREAMING: &[&str] = &["ExecutePlanStream", "ExecuteContentPlanStream"];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HttpMethod {
    pub service: String,
    pub rpc: String,
}

pub fn http_unary_methods() -> Vec<HttpMethod> {
    RpcMaturityTable::load()
        .expect("embedded rpc maturity table")
        .entries
        .iter()
        .filter(|entry| entry.classification == RpcClassification::Stable)
        .filter(|entry| !STREAMING.contains(&entry.rpc.as_str()))
        .map(|entry| HttpMethod {
            service: match entry.service.as_str() {
                "SekaiService" => "sekai.SekaiService".into(),
                "ChiseiService" => "chisei.ChiseiService".into(),
                other => other.to_string(),
            },
            rpc: entry.rpc.clone(),
        })
        .collect()
}

pub fn generate_typescript_client() -> String {
    let methods = method_literals();
    format!(
        r#"// Generated by sekai-chisei HTTP projection codegen. DO NOT EDIT.
// contract={contract}

export const HTTP_PROJECTION_CONTRACT = {contract_js};
export const HTTP_UNARY_METHODS = [
{methods}] as const;

export async function invokeHttpJson<T>(
  baseUrl: string,
  service: string,
  rpc: string,
  body: unknown,
  authorization: string,
  headers: Record<string, string> = {{}},
): Promise<T> {{
  const allowed = HTTP_UNARY_METHODS.some((method) => method.service === service && method.rpc === rpc);
  if (!allowed) throw new Error(`rpc is not on the HTTP/JSON projection: ${{service}}/${{rpc}}`);
  const response = await fetch(`${{baseUrl.replace(/\/$/, "")}}/${{service}}/${{rpc}}`, {{
    method: "POST",
    headers: {{
      "content-type": "application/json",
      authorization,
      ...headers,
    }},
    body: JSON.stringify(body ?? {{}}),
  }});
  const payload = await response.json();
  if (!response.ok) {{
    throw new Error(payload.message ?? response.statusText);
  }}
  return payload as T;
}}
"#,
        contract = HTTP_PROJECTION_CONTRACT,
        contract_js = js_string(HTTP_PROJECTION_CONTRACT),
        methods = methods,
    )
}

pub fn generate_python_client() -> String {
    let methods = http_unary_methods()
        .into_iter()
        .map(|method| {
            format!(
                "    ({service}, {rpc}),\n",
                service = py_string(&method.service),
                rpc = py_string(&method.rpc),
            )
        })
        .collect::<String>();
    format!(
        "{header}\n\nfrom __future__ import annotations\n\nimport json\nimport urllib.error\nimport urllib.request\nfrom typing import Any\n\nHTTP_PROJECTION_CONTRACT = {contract}\nHTTP_UNARY_METHODS = (\n{methods})\n\n\ndef invoke_http_json(\n    base_url: str,\n    service: str,\n    rpc: str,\n    body: dict[str, Any] | None,\n    authorization: str,\n    headers: dict[str, str] | None = None,\n) -> Any:\n    if (service, rpc) not in HTTP_UNARY_METHODS:\n        raise ValueError(f\"rpc is not on the HTTP/JSON projection: {{service}}/{{rpc}}\")\n    request = urllib.request.Request(\n        f\"{{base_url.rstrip('/')}}/{{service}}/{{rpc}}\",\n        data=json.dumps({{}} if body is None else body).encode(),\n        method=\"POST\",\n        headers={{\n            \"content-type\": \"application/json\",\n            \"authorization\": authorization,\n            **(headers or {{}}),\n        }},\n    )\n    try:\n        with urllib.request.urlopen(request) as response:\n            return json.load(response)\n    except urllib.error.HTTPError as error:\n        payload = json.loads(error.read().decode() or \"{{}}\")\n        raise RuntimeError(payload.get(\"message\") or error.reason) from error\n",
        header = "\"\"\"Generated by sekai-chisei HTTP projection codegen. DO NOT EDIT.\"\"\"",
        contract = py_string(HTTP_PROJECTION_CONTRACT),
        methods = methods,
    )
}

pub fn generate_rust_client() -> String {
    let methods = http_unary_methods()
        .into_iter()
        .map(|method| {
            format!(
                "        ({service}, {rpc}),\n",
                service = rust_string(&method.service),
                rpc = rust_string(&method.rpc),
            )
        })
        .collect::<String>();
    format!(
        r#"// Generated by sekai-chisei HTTP projection codegen. DO NOT EDIT.

pub const HTTP_PROJECTION_CONTRACT: &str = {contract};
pub const HTTP_UNARY_METHODS: &[(&str, &str)] = &[
{methods}];

pub fn http_path(service: &str, rpc: &str) -> Option<String> {{
    HTTP_UNARY_METHODS
        .iter()
        .find(|(hosted, method)| *hosted == service && *method == rpc)
        .map(|(hosted, method)| format!("{{hosted}}/{{method}}"))
}}
"#,
        contract = rust_string(HTTP_PROJECTION_CONTRACT),
        methods = methods,
    )
}

fn method_literals() -> String {
    http_unary_methods()
        .into_iter()
        .map(|method| {
            format!(
                "  {{ service: {service}, rpc: {rpc} }},\n",
                service = js_string(&method.service),
                rpc = js_string(&method.rpc),
            )
        })
        .collect()
}

fn js_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn py_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn rust_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;

    fn fixture(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/http_projection")
            .join(name)
    }

    #[test]
    fn generated_http_clients_match_goldens() {
        assert_eq!(
            generate_typescript_client(),
            fs::read_to_string(fixture("client.v1.ts")).unwrap()
        );
        assert_eq!(
            generate_python_client(),
            fs::read_to_string(fixture("client.v1.py")).unwrap()
        );
        assert_eq!(
            generate_rust_client(),
            fs::read_to_string(fixture("client.v1.rs")).unwrap()
        );
        assert_eq!(
            generate_typescript_client(),
            fs::read_to_string(
                PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("sdk/typescript/http.ts")
            )
            .unwrap()
        );
        assert_eq!(
            generate_python_client(),
            fs::read_to_string(
                PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("sdk/python/sekai_http.py")
            )
            .unwrap()
        );
        assert!(
            http_unary_methods()
                .iter()
                .any(|method| method.rpc == "EvaluateObjectSet")
        );
        assert!(
            !http_unary_methods()
                .iter()
                .any(|method| method.rpc == "ExecutePlanStream")
        );
    }
}
