-- Stable graph query and audit ordering for fresh and upgraded databases.
CREATE INDEX IF NOT EXISTS idx_objects_namespace_kind
    ON sekai_objects(namespace, kind, id);
CREATE INDEX IF NOT EXISTS idx_objects_namespace_external_id
    ON sekai_objects(namespace, external_id)
    WHERE external_id <> '';
DO $$
BEGIN
    IF EXISTS (
        SELECT external_id
        FROM sekai_objects
        WHERE kind = 'namespace' AND external_id LIKE 'namespace:%'
        GROUP BY external_id
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION USING
            MESSAGE = 'duplicate canonical namespace identities block graph parity migration',
            HINT = 'back up the database and resolve duplicate namespace:* external IDs before retrying; no graph rows were changed';
    END IF;
END;
$$;
CREATE UNIQUE INDEX IF NOT EXISTS idx_objects_canonical_namespace
    ON sekai_objects(external_id)
    WHERE kind = 'namespace' AND external_id LIKE 'namespace:%';
CREATE INDEX IF NOT EXISTS idx_links_relation_from_to
    ON sekai_links(relation, from_id, to_id, id);

ALTER TABLE sekai_object_changes
    ADD COLUMN IF NOT EXISTS audit_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS idx_object_changes_audit_seq
    ON sekai_object_changes(audit_seq);
CREATE INDEX IF NOT EXISTS idx_object_changes_object_order
    ON sekai_object_changes(object_id, timestamp DESC, audit_seq DESC);

-- Match SQLite's finite-f64 numeric ordering without allowing malformed or
-- out-of-range user property strings to abort an entire graph query.
CREATE OR REPLACE FUNCTION sekai_is_numeric_text(value TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
STRICT
AS $$
BEGIN
    PERFORM BTRIM(value)::DOUBLE PRECISION;
    RETURN BTRIM(value) ~
        '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)([eE][+-]?[0-9]+)?$';
EXCEPTION
    WHEN invalid_text_representation OR numeric_value_out_of_range THEN
        RETURN FALSE;
END;
$$;
